@echo off
set PGPASSWORD=postgres
echo Testing connection...
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -h localhost -p 5432 -U postgres -d superecommanager -c "SELECT 'Connection OK' as status;"
echo Dropping shared schema...
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -h localhost -p 5432 -U postgres -d superecommanager -c "DROP SCHEMA IF EXISTS shared CASCADE;"
echo Dropping public schema...
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -h localhost -p 5432 -U postgres -d superecommanager -c "DROP SCHEMA IF EXISTS public CASCADE;"
echo Creating public schema...
"C:\Program Files\PostgreSQL\18\bin\psql.exe" -h localhost -p 5432 -U postgres -d superecommanager -c "CREATE SCHEMA public;"
echo Done!
